development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
  username: ben
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000
  username: ben

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
  username: ben

